"""empty message

Revision ID: 93882ec78efd
Revises:
Create Date: 2024-05-11 14:40:40.985894

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "93882ec78efd"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bot",
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("last_updated_at", sa.DateTime(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("organization_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("query_selector", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "environment",
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("last_updated_at", sa.DateTime(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("bot_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["bot_id"],
            ["bot.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "suite",
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("last_updated_at", sa.DateTime(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("bot_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("default_success_criteria", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("default_iteration_count", sa.Integer(), nullable=False),
        sa.Column("default_variant_count", sa.Integer(), nullable=False),
        sa.Column(
            "reporting_comparison_configuration",
            sa.Enum("MRSE", "MRDE", "SSR", name="reportingconfigurationenum"),
            nullable=False,
        ),
        sa.Column("reporting_comparison_suite_run_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("reporting_comparison_environment_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["bot_id"],
            ["bot.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "suite_run",
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("last_updated_at", sa.DateTime(), nullable=False),
        sa.Column("suite_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("environment_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "initiation_type", sa.Enum("MANUAL", "AUTOMATED", "SCHEDULED", name="initiationtypeenum"), nullable=False
        ),
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("RUNNING", "PASS", "MIXED", "FAIL", "STOPPED", "ERROR", "SKIPPED", name="runstatusenum"),
            nullable=False,
        ),
        sa.Column("status_info", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("pass_rate", sa.Float(), nullable=True),
        sa.Column("average_replayed_elapsed_seconds", sa.Float(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["environment_id"],
            ["environment.id"],
        ),
        sa.ForeignKeyConstraint(
            ["suite_id"],
            ["suite.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "test",
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("last_updated_at", sa.DateTime(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("suite_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("success_criteria", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("use_default_success_criteria", sa.Boolean(), nullable=False),
        sa.Column("iteration_count", sa.Integer(), nullable=False),
        sa.Column("use_default_iteration_count", sa.Boolean(), nullable=False),
        sa.Column("variant_count", sa.Integer(), nullable=False),
        sa.Column("use_default_variant_count", sa.Boolean(), nullable=False),
        sa.Column("full_run_enabled", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["suite_id"],
            ["suite.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "baseline",
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("last_updated_at", sa.DateTime(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("html_blob", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("test_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("conversation_json", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["test_id"],
            ["test.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "test_run",
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("last_updated_at", sa.DateTime(), nullable=False),
        sa.Column("environment_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("test_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "initiation_type", sa.Enum("MANUAL", "AUTOMATED", "SCHEDULED", name="initiationtypeenum"), nullable=False
        ),
        sa.Column("suite_run_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("RUNNING", "PASS", "MIXED", "FAIL", "STOPPED", "ERROR", "SKIPPED", name="runstatusenum"),
            nullable=False,
        ),
        sa.Column("status_info", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("pass_rate", sa.Float(), nullable=True),
        sa.Column("average_replayed_elapsed_seconds", sa.Float(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["environment_id"],
            ["environment.id"],
        ),
        sa.ForeignKeyConstraint(
            ["suite_run_id"],
            ["suite_run.id"],
        ),
        sa.ForeignKeyConstraint(
            ["test_id"],
            ["test.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "variant",
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("last_updated_at", sa.DateTime(), nullable=False),
        sa.Column("test_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("replay_json", sa.JSON(), nullable=True),
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["test_id"],
            ["test.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "variant_run",
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("last_updated_at", sa.DateTime(), nullable=False),
        sa.Column("test_run_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("variant_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "initiation_type", sa.Enum("MANUAL", "AUTOMATED", "SCHEDULED", name="initiationtypeenum"), nullable=False
        ),
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("RUNNING", "PASS", "MIXED", "FAIL", "STOPPED", "ERROR", "SKIPPED", name="runstatusenum"),
            nullable=False,
        ),
        sa.Column("status_info", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("pass_rate", sa.Float(), nullable=True),
        sa.Column("average_replayed_elapsed_seconds", sa.Float(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["test_run_id"],
            ["test_run.id"],
        ),
        sa.ForeignKeyConstraint(
            ["variant_id"],
            ["variant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "evaluation",
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("last_updated_at", sa.DateTime(), nullable=False),
        sa.Column("variant_run_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("html_blob", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("replayed_elapsed_seconds", sa.Float(), nullable=False),
        sa.Column(
            "initiation_type", sa.Enum("MANUAL", "AUTOMATED", "SCHEDULED", name="initiationtypeenum"), nullable=False
        ),
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("conversation_json", sa.JSON(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("RUNNING", "PASS", "MIXED", "FAIL", "STOPPED", "ERROR", "SKIPPED", name="runstatusenum"),
            nullable=False,
        ),
        sa.Column("status_info", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("pass_baseline_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["variant_run_id"],
            ["variant_run.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("evaluation")
    op.drop_table("variant_run")
    op.drop_table("variant")
    op.drop_table("test_run")
    op.drop_table("baseline")
    op.drop_table("test")
    op.drop_table("suite_run")
    op.drop_table("suite")
    op.drop_table("environment")
    op.drop_table("bot")
    # ### end Alembic commands ###
